version: '3.5'

services:
  db:
    container_name: database_name
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: database_name
      POSTGRES_USER: database_user
      POSTGRES_PASSWORD: database_password
    volumes:
      - ./data/db:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  api:
    container_name: api_name
    build:
      context: ./configs/docker/
      dockerfile: Dockerfile
    env_file: 
      - ./.env
    ports:
      - '3000:3000'
    depends_on:
      - db
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
