version: '3.9'

services:
  api:
    container_name: api_caalliope
    build:
      dockerfile: Dockerfile.dev
    env_file:
      - ./.env.local
    ports:
      - '3001:3001'
    volumes:
      - .:/usr/src/app
      - node_modules:/usr/src/app/node_modules
      - uploads:/usr/src/app/uploads
      #- app:/usr/src/app
      #- node_modules:/usr/src/app/node_modules  # Synchronise le répertoire de travail avec le conteneur
    command: npm run dev
    depends_on:
      - db_dev
      - db_test

  db_dev:
    container_name: database_caalliope_dev
    image: postgres:15
    environment:
      POSTGRES_DB: database_caalliope_dev
      POSTGRES_USER: caalliope_dev
      POSTGRES_PASSWORD: caalliope_dev*2024!
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  db_test:
    container_name: database_caalliope_test
    image: postgres:15
    environment:
      POSTGRES_DB: database_caalliope_test
      POSTGRES_USER: caalliope_test
      POSTGRES_PASSWORD: caalliope_test*2024!
    ports:
      - '5433:5432'
    depends_on:
      - db_dev

  interface_db:
    container_name: interface_db_caalliope_dev
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: caalliope.dev@gmail.com
      PGADMIN_DEFAULT_PASSWORD: caalliope_dev*2024!
      PGADMIN_CONFIG_ENHANCED_COOKIE_PROTECTION: 'False'
      PGADMIN_DISABLE_POSTFIX: 'True'
    ports:
      - '5050:80'
    depends_on:
      - db_dev

volumes:
  postgres_data:
  node_modules:
  uploads:
