# Utilisez une image Node officielle comme image de base
FROM node:18

# Créez un répertoire pour les uplaods
RUN mkdir -p /usr/src/app/uploads/avatars
RUN mkdir -p /usr/src/app/uploads/covers

# Créez un répertoire pour l'application
RUN mkdir -p /usr/src/app

# Créez un répertoire de travail
WORKDIR /usr/src/app

# Copiez le package.json et le package-lock.json
COPY package*.json ./

# Installez les dépendances
RUN npm install

# Copiez le reste des fichiers de l'application
COPY . .

# Exposez le port de l'application
EXPOSE 3001

# Démarrez l'application
CMD ["npm", "run", "dev"]
